config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :properties
  resources :bills
  resources :residents
  
  get 'about' => "pages#about"
  get 'part' => "pages#part"
  get 'bills' => "bills#index"
  get 'residents' => "residents#index"
  get 'properties' => "properties#index"
  get 'dashboard' => "pages#dashboard"

  root 'pages#home'

end

app/models/property.rb
class Property < ActiveRecord::Base
	belongs_to :user
	has_one :resident
	has_many :bills
	geocoded_by :address_one
	after_validation :geocode
	validates_presence_of :address_one, :addresstype, :city, :state
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action :signed_in_user, only: [:index, :show, :edit, :update, :destroy, :create, :new]
	before_action :find_property, only: [:show, :edit, :update, :destroy]

	def index
		user_id = User.find(current_user)
		@properties = user_id.properties.all
		#.order("created_at ASC")
		bills = Bill.all
		@current_user_bills = bills.where("user_id = '?'", current_user)
		residents = Resident.all
		@current_user_residents = residents.where("user_id = '?'", current_user)
	end

	def show  
		property = find_property
		@hash = Gmaps4rails.build_markers @property do |u, m|
			m.lat u.geocode.first rescue nil
			m.lng u.geocode.second rescue nil
			m.json({ :id => u.id })
		end
		@bills = Bill.all
		if @property.user_id == current_user.id
			# ..
		else
			return redirect_to root_path, :notice => "You dont have access to this property."
		end
		@residents = Resident.find(@property.resident_id) rescue nil

	end

	def new
		@property = Property.new
	end

	def create
		@property = Property.new(property_params)
		@property.user_id = current_user.id
		if @property.save
			redirect_to @property
		else
			render "new"
		end
	end

	def edit
		if @property.user_id == current_user.id
			# ...
		else
			redirect_to root_path, :notice => "You dont have access to this property."
		end
	end

	def update
		if @property.update(property_params)
			redirect_to @property
		else
			render "edit"
		end
	end

	def destroy
		if @property.user_id == current_user.id
			
		else
			redirect_to root_path, :notice => "You dont have access to this property."
		end
		@property.destroy
		redirect_to properties_path
	end

	private

	def property_params
		params.require(:property).permit(:address_one, :address_two, :addresstype, :city, :state, :zip_code, :rent, :vacancy, :resident_id, :latitude, :longitude)
	end

	def find_property
		@property = Property.find(params[:id]) rescue nil
	end

	def signed_in_user
	    unless signed_in?
	        redirect_to root_path, :notice => "You must be logged in to view your properties."
    	end
    end

    def sort_column2
    	Property.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def us_states
	  [
	  	['Not in the US', 'None'],
	    ['Alabama', 'AL'],
	    ['Alaska', 'AK'],
	    ['Arizona', 'AZ'],
	    ['Arkansas', 'AR'],
	    ['California', 'CA'],
	    ['Colorado', 'CO'],
	    ['Connecticut', 'CT'],
	    ['Delaware', 'DE'],
	    ['District of Columbia', 'DC'],
	    ['Florida', 'FL'],
	    ['Georgia', 'GA'],
	    ['Hawaii', 'HI'],
	    ['Idaho', 'ID'],
	    ['Illinois', 'IL'],
	    ['Indiana', 'IN'],
	    ['Iowa', 'IA'],
	    ['Kansas', 'KS'],
	    ['Kentucky', 'KY'],
	    ['Louisiana', 'LA'],
	    ['Maine', 'ME'],
	    ['Maryland', 'MD'],
	    ['Massachusetts', 'MA'],
	    ['Michigan', 'MI'],
	    ['Minnesota', 'MN'],
	    ['Mississippi', 'MS'],
	    ['Missouri', 'MO'],
	    ['Montana', 'MT'],
	    ['Nebraska', 'NE'],
	    ['Nevada', 'NV'],
	    ['New Hampshire', 'NH'],
	    ['New Jersey', 'NJ'],
	    ['New Mexico', 'NM'],
	    ['New York', 'NY'],
	    ['North Carolina', 'NC'],
	    ['North Dakota', 'ND'],
	    ['Ohio', 'OH'],
	    ['Oklahoma', 'OK'],
	    ['Oregon', 'OR'],
	    ['Pennsylvania', 'PA'],
	    ['Puerto Rico', 'PR'],
	    ['Rhode Island', 'RI'],
	    ['South Carolina', 'SC'],
	    ['South Dakota', 'SD'],
	    ['Tennessee', 'TN'],
	    ['Texas', 'TX'],
	    ['Utah', 'UT'],
	    ['Vermont', 'VT'],
	    ['Virginia', 'VA'],
	    ['Washington', 'WA'],
	    ['West Virginia', 'WV'],
	    ['Wisconsin', 'WI'],
	    ['Wyoming', 'WY']
	  ]
	end


	def all_residents_map
		res_list = [["None", "None"]]
		user_id = User.find(current_user)
		residents = Resident.where("user_id = '?'", current_user)
		residents.each { |b| 
			res_list << [b.name, b.id] }
		return res_list
	end

	def current_resident_address(resident_id) 
		property_address = nil
		property = Property.where("resident_id = '?'", resident_id)  
		property.each { |b| 
			property_address = b.address_one + ", " + b.address_two }
		return property_address
	end

	def current_resident(a_resident_id)
		resident_name = nil
		residents = Resident.where("id = '?'", a_resident_id)
		residents.each { |b| 
			resident_name = b.name }
		return resident_name
	end

	def property_id_to_address(property_id)
		property_address = nil
		property = Property.where("id= '?'", property_id)  
		property.each { |b| 
			property_address = b.address_one + ", " + b.address_two }
		return property_address
	end
end

app/views/properties/dashboard.html.erb
<h3><span class="label label-success" align="right">الموقع لا يزال قيد التحديث، يرجى التواصل بالمشاكل والإقتراحات عبر تويتر او عبر البريد الإلكتروني، مزيد من المعلومات <%= link_to "هنا", "https://aqaraat-alioh-6.c9.io/part"%></span></h3>



<h3> Your Properties: </h3>
Red label = not available
<table class="table table-striped" border="0" style="width:100%" id="protable">
	<thead>
		<tr>
			<th>#</th>
			<th>Street Address</th>
			<th>Suite/Apt #</th>
			<th>Address Type</th>
			<th>City</th>
			<th>State</th>
			<th>Zip code</th>
			<th>Rent</th>
			<th>Current Resident</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% count = 1%>
		<% @properties.each do |pro| %>
		<% if  pro.vacancy == "No"%>
			<tr class="danger">
				<td><%= count %></td>
				<td><%= pro.address_one %></td>
				<td><%= pro.address_two %></td>
				<td><%= pro.addresstype %></td>
				<td><%= pro.city %></td>
				<td><%= pro.state %></td>
				<td><%= pro.zip_code %></td>
				<td>$<%= pro.rent %></td>
				<td><%= current_resident(pro.resident_id) %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
					  <div type="button" class="btn btn-default"><%= link_to "View", pro, 'data-no-turbolink' => true %></div>
					  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_property_path(pro)%></div>
					  <div type="button" class="btn btn-default"><%= link_to "Delete", property_path(pro), method: :delete, data: { confirm: "Are you sure you want to delete this property?" }%></div>
					</div>
				</td>
				<% count+=1 %>
			</tr>
		<% else %>
			<tr>
				<td><%= count %></td>
				<td><%= pro.address_one %></td>
				<td><%= pro.address_two %></td>
				<td><%= pro.addresstype %></td>
				<td><%= pro.city %></td>
				<td><%= pro.state %></td>
				<td><%= pro.zip_code %></td>
				<td>$<%= pro.rent %></td>
				<td><%= current_resident(pro.resident_id) %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
					  <div type="button" class="btn btn-default"><%= link_to "View", pro, 'data-no-turbolink' => true %></div>
					  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_property_path(pro)%></div>
					  <div type="button" class="btn btn-default"><%= link_to "Delete", property_path(pro), method: :delete, data: { confirm: "Are you sure you want to delete this property?" }%></div>
					</div>
				</td>
			<% count+=1 %>
			</tr>
		<% end %>
		<% end %>
	</tbody>
</table>

<!-- <a class="btn btn-primary" href="/properties/new">Add new property</a> -->
<div class="form-actions"> 
	<%= link_to "Add new property", new_property_path, class: "btn btn-primary" %>
</div>

<h3> Your Bills: <%= link_to image_tag("external.gif"), bills_path, 'data-no-turbolink' => true %> </h3> 
<table class="table table-striped" border="0" style="width:100%" id="billstable">
	<thead>
		<tr>
			<th>#</th>
			<th>Bill to</th>
			<th>Due Date</th>
			<th>Bill Type</th>
			<th>Status</th>
			<th>Amount</th>
			<th>Property Address</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% count = 1 %>
		<% @current_user_bills.each do |b| %>
			<% if  b.status == "Unpaid" and b.duedate < Time.zone.now %>
				<tr class="danger">
					<td><%= count %></td>
					<td><%= current_resident(b.resident_id) %></td>
					<td><%= b.duedate %></td>
					<td><%= b.billtype %></td>
					<td><%= b.status %></td>
					<td>$<%= b.amount %></td>
					<td><%= property_id_to_address(b.property_id) %></td>
					<td>
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
						  <div type="button" class="btn btn-default"><%= link_to "View", b, 'data-no-turbolink' => true %></div>
						  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_bill_path(b)%></div>
						  <div type="button" class="btn btn-default"><%= link_to "Delete", bill_path(b), method: :delete, data: { confirm: "Are you sure you want to delete this bill?" }%></div>
						</div>
					</td>
				<% count +=1 %>
				</tr>
			<% else %>
				<tr>
					<td><%= count %></td>
					<td><%= current_resident(b.resident_id) %></td>
					<td><%= b.duedate %></td>
					<td><%= b.billtype %></td>
					<td><%= b.status %></td>
					<td>$<%= b.amount %></td>
					<td><%= property_id_to_address(b.property_id) %></td>
					<td>
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
						  <div type="button" class="btn btn-default"><%= link_to "View", b, 'data-no-turbolink' => true %></div>
						  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_bill_path(b)%></div>
						  <div type="button" class="btn btn-default"><%= link_to "Delete", bill_path(b), method: :delete, data: { confirm: "Are you sure you want to delete this bill?" }%></div>
						</div>
					</td>
					<% count += 1 %>
				</tr>
			<% end %>
			<% end %>
		<% if count == 0  %>
			<p> You dont have any bills </p>
		<% end %>
	</tbody>
</table>
<div class="form-actions">
	<%= link_to "Add new bill", new_bill_path, class: "btn btn-primary" %>
</div>

<h3> Your Residents: <%= link_to image_tag("external.gif"), residents_path, 'data-no-turbolink' => true %></h3>

<table class="table table-striped" border="0" style="width:100%" id="restable">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>In Property</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% count = 1%>
		<% @current_user_residents.each do |b| %>
			<td><%= count %></td>
			<td><%= b.name %></td>
			<td><%= current_resident_address(b.id) %></td>
			<td>
				<div class="btn-group btn-group-xs" role="group" aria-label="...">
					<div type="button" class="btn btn-default"><%= link_to "View", b %></div>
					<div type="button" class="btn btn-default"><%= link_to "Edit", edit_resident_path(b)%></div>
					<div type="button" class="btn btn-default"><%= link_to "Delete", resident_path(b), method: :delete, data: { confirm: "Are you sure you want to delete this resident?" }%></div>
				</div>
			</td>
			<% count+=1 %>
		</tbody>
	<% end %>
</table>

<!-- <a class="btn btn-primary" href="/properties/new">Add new property</a> -->
<div class="form-actions">
	<%= link_to "Add new resident", new_resident_path, class: "btn btn-primary" %>
</div>

app/views/properties/edit.html.erb
<h1> Edit Property </h1>
<div class="row">
<%= simple_form_for(@property, html: { class: "form-horizontal"}) do |f| %>
	<%= f.input :address_one, label: "Street Address", required: true, :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :address_two, label: "Suite/Apt #", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :addresstype, collection: [ "House", "Apartment" ], required: true, label: "Address Type", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :city, label: "City", required: true, :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :state, label: "State", required: true, :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :zip_code, label: "Zip code", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :rent, label: "Monthly rent", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :vacancy, collection: [ "Yes", "No" ], label: "Vacancy", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :resident_id, collection: all_residents_map, :input_html => {:style=> 'width: 250px'} %>

  <div class="form-actions">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
    <%= link_to "Back", properties_path, class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/properties/index.html.erb
<h3> Your Properties: </h3>
Red label = not available

<table class="table table-responsive" border="0" style="width:100%" id="protable">
	<thead>
		<tr>
			<th>#</th>
			<th>Street Address</th>
			<th>Suite/Apt #</th>
			<th>Address Type</th>
			<th>City</th>
			<th>State</th>
			<th>Zip code</th>
			<th>Rent</th>
			<th>Current Resident</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% count = 1%>
		<% @properties.each do |pro| %>
		<% if  pro.vacancy == "No" %>
			<tr class="danger">
				<td><%= count %></td>
				<td><%= pro.address_one %></td>
				<td><%= pro.address_two %></td>
				<td><%= pro.addresstype %></td>
				<td><%= pro.city %></td>
				<td><%= pro.state %></td>
				<td><%= pro.zip_code %></td>
				<td>$<%= pro.rent %></td>
				<td><%= current_resident(pro.resident_id) %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
					  <div type="button" class="btn btn-default"><%= link_to "View", pro, 'data-no-turbolink' => true %></div>
					  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_property_path(pro)%></div>
					  <div type="button" class="btn btn-default"><%= link_to "Delete", property_path(pro), method: :delete, data: { confirm: "Are you sure you want to delete this property?" }%></div>
					</div>
				</td>
				<% count+=1 %>
			</tr>
		<% else %>
			<tr>
				<td><%= count %></td>
				<td><%= pro.address_one %></td>
				<td><%= pro.address_two %></td>
				<td><%= pro.addresstype %></td>
				<td><%= pro.city %></td>
				<td><%= pro.state %></td>
				<td><%= pro.zip_code %></td>
				<td>$<%= pro.rent %></td>
				<td><%= current_resident(pro.resident_id) %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
					  <div type="button" class="btn btn-default"><%= link_to "View", pro, 'data-no-turbolink' => true %></div>
					  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_property_path(pro)%></div>
					  <div type="button" class="btn btn-default"><%= link_to "Delete", property_path(pro), method: :delete, data: { confirm: "Are you sure you want to delete this property?" }%></div>
					</div>
				</td>
			<% count+=1 %>
			</tr>
		<% end %>
		<% end %>
	</tbody>
</table>

<!-- <a class="btn btn-primary" href="/properties/new">Add new property</a> -->
<div class="form-actions"> 
	<%= link_to "Add new property", new_property_path, class: "btn btn-primary" %>
</div>

<!-- <h3> Your Bills: <%= link_to image_tag("external.gif"), bills_path, 'data-no-turbolink' => true %> </h3> 
<table class="table table-striped" border="0" style="width:100%" id="billstable">
	<thead>
		<tr>
			<th>#</th>
			<th>Bill to</th>
			<th>Due Date</th>
			<th>Bill Type</th>
			<th>Status</th>
			<th>Amount</th>
			<th>Property Address</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% count = 1 %>
		<% @current_user_bills.each do |b| %>
			<% if  b.status == "Unpaid" and b.duedate < Time.zone.now %>
				<tr class="danger">
					<td><%= count %></td>
					<td><%= current_resident(b.resident_id) %></td>
					<td><%= b.duedate %></td>
					<td><%= b.billtype %></td>
					<td><%= b.status %></td>
					<td>$<%= b.amount %></td>
					<td><%= property_id_to_address(b.property_id) %></td>
					<td>
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
						  <div type="button" class="btn btn-default"><%= link_to "View", b, 'data-no-turbolink' => true %></div>
						  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_bill_path(b)%></div>
						  <div type="button" class="btn btn-default"><%= link_to "Delete", bill_path(b), method: :delete, data: { confirm: "Are you sure you want to delete this bill?" }%></div>
						</div>
					</td>
				<% count +=1 %>
				</tr>
			<% else %>
				<tr>
					<td><%= count %></td>
					<td><%= current_resident(b.resident_id) %></td>
					<td><%= b.duedate %></td>
					<td><%= b.billtype %></td>
					<td><%= b.status %></td>
					<td>$<%= b.amount %></td>
					<td><%= property_id_to_address(b.property_id) %></td>
					<td>
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
						  <div type="button" class="btn btn-default"><%= link_to "View", b, 'data-no-turbolink' => true %></div>
						  <div type="button" class="btn btn-default"><%= link_to "Edit", edit_bill_path(b)%></div>
						  <div type="button" class="btn btn-default"><%= link_to "Delete", bill_path(b), method: :delete, data: { confirm: "Are you sure you want to delete this bill?" }%></div>
						</div>
					</td>
					<% count += 1 %>
				</tr>
			<% end %>
			<% end %>
		<% if count == 0  %>
			<p> You dont have any bills </p>
		<% end %>
	</tbody>
</table>
<div class="form-actions">
	<%= link_to "Add new bill", new_bill_path, class: "btn btn-primary" %>
</div>

<h3> Your Residents: <%= link_to image_tag("external.gif"), residents_path, 'data-no-turbolink' => true %></h3>

<table class="table table-striped" border="0" style="width:100%" id="restable">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>In Property</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% count = 1%>
		<% @current_user_residents.each do |b| %>
			<td><%= count %></td>
			<td><%= b.name %></td>
			<td><%= current_resident_address(b.id) %></td>
			<td>
				<div class="btn-group btn-group-xs" role="group" aria-label="...">
					<div type="button" class="btn btn-default"><%= link_to "View", b %></div>
					<div type="button" class="btn btn-default"><%= link_to "Edit", edit_resident_path(b)%></div>
					<div type="button" class="btn btn-default"><%= link_to "Delete", resident_path(b), method: :delete, data: { confirm: "Are you sure you want to delete this resident?" }%></div>
				</div>
			</td>
			<% count+=1 %>
		</tbody>
	<% end %>
</table>

<a class="btn btn-primary" href="/properties/new">Add new property</a>
<div class="form-actions">
	<%= link_to "Add new resident", new_resident_path, class: "btn btn-primary" %>
</div> -->

app/views/properties/new.html.erb
<h3>New Property </h3>
<div class="row">
	<%= simple_form_for(@property, html: { class: "form-horizontal"}) do |f| %>
	<%= f.input :address_one, label: "Street Address", required: true, :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :address_two, label: "Suite/Apt #", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :addresstype, collection: [ "House", "Apartment" ], selected: "House", required: true, label: "Address Type", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :city, label: "City", required: true, :input_html => {:style => 'width: 250px'} %>
	<%= f.input :state, collection: us_states, required: true, label: "State", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :zip_code, label: "Zip code", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :rent, label: "Monthly rent", :input_html => {:style=> 'width: 250px'} %>
	<%= f.input :vacancy, collection: [ "Yes", "No" ], label: "Vacancy", selected: "Yes", :input_html => {:style=> 'width: 250px'} %>
    <%= f.input :resident_id, collection: all_residents_map, selected: "none", :input_html => {:style=> 'width: 250px'} %>
    <% f.input :latitude, label: "latitude", :input_html => {:style=> 'width: 250px'} %>
    <% f.input :longitude, label: "longitude", :input_html => {:style=> 'width: 250px'} %>


  <div class="form-actions">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
	<%= link_to "Back", properties_path, class: "btn btn-primary" %>
  </div>
</div>
<% end %>