config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :properties
  resources :bills
  resources :residents
  
  get 'about' => "pages#about"
  get 'part' => "pages#part"
  get 'bills' => "bills#index"
  get 'residents' => "residents#index"
  get 'properties' => "properties#index"
  get 'dashboard' => "pages#dashboard"

  root 'pages#home'

end

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">

<div class="row-fluid">
  <div class="col-md-4 col-xs-15 col-sm-12">
	<h1>Welecome to eProperty!</h1>
	<img src="https://pbs.twimg.com/profile_images/2187681201/profile.jpg" width=250 hieght=250/>
  </div>
  <div class="col-md-8 col-xs-15 col-sm-12">
    <br>
    <br>
    <br>
  	<p> eProperty is an easy way to manage your property </p>
    <p> What you can do with eProperty: 
    <ul>
      <li> Store property details.
      <li> Keep record of history payment.
      <li> Keep records of each property bills.
    </ul>
    <br>
    <br>
    <% if signed_in? %>
      <%else%>
      <p>
      <a class="btn btn-primary btn-lg" href="users/sign_up" role="button">Sign up!</a></p>
      <%end%>
  </div>

</div>

<!-- <div class="row">
  <div class="span9">
    Level 1 column
    <div class="row">
      <div class="span6">Level 2</div>
      <div class="span3">Level 2</div>
    </div>
  </div>
</div> -->


</html>

app/views/pages/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<br>
<br>
<br>
<div class="container-fluid" align="center">
  <div class="col-md-4 col-xs-15 col-sm-12">
    <%= link_to image_tag("res.png"), residents_path, 'data-no-turbolink' => true %>
  </div>
  <div class="col-md-4 col-xs-15 col-sm-12">
    <%= link_to image_tag("bill.png"), bills_path, 'data-no-turbolink' => true %>
  </div>
  <div class="col-md-4 col-xs-15 col-sm-12">
    <%= link_to image_tag("pro.png"), properties_path, 'data-no-turbolink' => true %>
  </div>
</div>
<br>
<br>
<br>
<br>
<p><h6><i> * Icons designed by Freepik.com. </i></h6></p>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<div class="jumbotron">
  <h1>Welcome to eProperty!</h1>
  <p>An easy way to manage your property online!</p>
  <p><a class="btn btn-primary btn-lg" href="/about" role="button">Learn more</a></p>
</div>


</html>

app/views/pages/part.html.erb
<!DOCTYPE html>
<html dir="rtl" lang="ar">

<div class="row-fluid">
  <div class="col-md-4 col-xs-15 col-sm-12">
	<h1>مرحبًا</h1>
  </div>
  <div class="col-md-8 col-xs-15 col-sm-12">
    <br>
    <br>
    <br>
  	<p> التطبيق عبارة عن مشروع جامعي اعمل عليه حاليًا، الشريحه المستهدفة اي شخص يملك مجموعه قليله من العقارات </p>
    <p> ويريد متابعتها بنفسه والإستغناء عن مكتب العقار</p>
    <p>نقاط مهمه:</p>
    <ul>
      <li> توجد مشكلة بسيطه بصفحة عرض العقار وصفحة إحصائيات الفواتير، قد تحتاج لتحديث الصفحه لعرض الصور.
      <li> يجب استخدام عنوان صحيح مطابق لما هو في قوقل ماب لكي تظهر الخريطة في صفحة العقار.
      <li> دعم العربية ليس كامل حتى الآن.
    </ul>
    <br>
    <p> اتمنى تنبيهي في حال واجهتك اخطاء، مشاكل، او اذا كان لديك اقتراحات ممكن ان تُحسن التطبيق!</p>
    <p> يمكن التواصل معي عبر تويتر <%= link_to "alioh", "https://twitter.com/alioh"%></p>
    <p> او البريد: ali.alohali@gmail.com</p>
    <br>
    <p> شكرًا!</p>
    <br>
    <p><a class="btn btn-primary btn-lg" href="users/sign_up" role="button">سجل!</a></p>
  </div>
</div>